spring.data.mongodb.uri=mongodb://localhost:27017/promptlibrary
spring.data.mongodb.auto-index-creation=true

#spring.security.user.name=admin
#spring.security.user.password=admin123


jwt.secret=4c95cbb41f83a93e5cbf0d7a2b8e8f154e39b7d0f31f2a9f6b8c7d5e4f3a2b1c
jwt.expiration=86400000